-- 
WITH RECURSIVE CTE AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT E.ID, E.PARENT_ID, CTE.GENERATION + 1
    FROM CTE JOIN ECOLI_DATA E
    WHERE CTE.ID = E.PARENT_ID
)

SELECT ID
FROM CTE
WHERE GENERATION = 3
ORDER BY ID ASC