-- 상품코드 별 매출액(판매가 * 판매량) 합계를 출력
-- 1. 매출액을 기준으로 내림차순 정렬
-- 2. 상품코드를 기준으로 오름차순 정렬
SELECT PRODUCT_CODE, SUM(PRICE * SALES_AMOUNT) AS SALES
FROM PRODUCT NATURAL JOIN OFFLINE_SALE
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE ASC