 -- 년, 월, 성별 별로 상품을 구매한 회원수를 집계
 -- 년, 월, 성별을 기준으로 오름차순 정렬
 -- 성별 정보가 없는 경우 결과에서 제외
 
 SELECT YEAR(SALES_DATE) as YEAR, MONTH(SALES_DATE) as MONTH, GENDER, COUNT(DISTINCT o.USER_ID) as USERS
 FROM ONLINE_SALE o
 JOIN USER_INFO u ON o.USER_ID = u.USER_ID
 WHERE GENDER IS NOT NULL
 GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
 ORDER BY YEAR ASC, MONTH ASC, GENDER ASC