-- 자식이 없는 개체의 수, 세대 출력
-- 세대에 대해 오름차순

WITH RECURSIVE TMP AS (
    SELECT ID, PARENT_ID, 1 as GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT E.ID, E.PARENT_ID, TMP.GENERATION + 1
    FROM TMP JOIN ECOLI_DATA E
    WHERE TMP.ID = E.PARENT_ID
)

SELECT COUNT(*) AS COUNT, GENERATION
FROM TMP
WHERE ID NOT IN (
    SELECT DISTINCT PARENT_ID
    FROM TMP
    WHERE PARENT_ID IS NOT NULL
)
GROUP BY GENERATION
ORDER BY 2