-- FOOD_PRODUCT와 FOOD_ORDER 
-- 생산일자가 2022년 5월인 식품
-- 식품 ID, 식품 이름, 총매출을 조회
-- 1. 총매출을 기준으로 내림차순 정렬
-- 2. 식품 ID를 기준으로 오름차순 정렬

SELECT PRODUCT_ID, PRODUCT_NAME, SUM(AMOUNT * PRICE) AS TOTAL_SALES
FROM FOOD_ORDER NATURAL JOIN FOOD_PRODUCT
WHERE PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31'
GROUP BY PRODUCT_ID, PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC