SELECT FLAVOR
FROM (SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER_SUM
FROM (
  SELECT FLAVOR, TOTAL_ORDER FROM JULY
  UNION ALL
  SELECT FLAVOR, TOTAL_ORDER FROM FIRST_HALF
) AS E
GROUP BY FLAVOR) O
ORDER BY TOTAL_ORDER_SUM DESC
LIMIT 3;
