-- 7월 아이스크림 총 주문량과 상반기의 아이스크림 총 주문량을 더한 값 순 정렬
-- 상위 3개 맛

SELECT F.FLAVOR
FROM FIRST_HALF F 
JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) AS FLAVOR_TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR) J
WHERE F.FLAVOR = J.FLAVOR
ORDER BY F.TOTAL_ORDER + J.FLAVOR_TOTAL_ORDER DESC
LIMIT 3

