SELECT C.ID,
       C.GENOTYPE,
       X.PARENT_GENOTYPE
FROM ECOLI_DATA C
JOIN (
    SELECT ID, GENOTYPE AS PARENT_GENOTYPE
    FROM ECOLI_DATA
) X ON X.ID = C.PARENT_ID
WHERE (C.GENOTYPE & X.PARENT_GENOTYPE) = X.PARENT_GENOTYPE
ORDER BY C.ID;
