-- ANIMAL_OUTS 테이블의 ANIMAL_ID는 ANIMAL_INS의 ANIMAL_ID의 외래 키
-- 보호 시작일(INS -> DATETIME)보다 입양일(OUTS -> DATETIME)이 더 빠른 동물 찾기
-- 동물의 아이디와 이름
-- 보호 시작일이 빠른 순

SELECT I.ANIMAL_ID AS ANIMAL_ID, I.NAME AS NAME
FROM ANIMAL_INS I JOIN ANIMAL_OUTS O
ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.DATETIME > O.DATETIME
ORDER BY I.DATETIME ASC