-- 대여 시작일을 기준으로 2022년 8월부터 2022년 10월까지 총 대여 횟수가 5회 이상인 자동차
-- 해당 기간 동안의 월별 자동차 ID 별 총 대여 횟수(컬럼명: RECORDS) 리스트를 출력
-- 월을 기준으로 오름차순 정렬
-- 자동차 ID를 기준으로 내림차순 정렬
-- 특정 월의 총 대여 횟수가 0인 경우에는 결과에서 제외

SELECT MONTH(H.START_DATE) AS MONTH, H.CAR_ID AS CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H, (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-11-01'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
) AS T
WHERE H.CAR_ID = T.CAR_ID AND (START_DATE BETWEEN '2022-08-01' AND '2022-11-01')
GROUP BY H.CAR_ID, MONTH(H.START_DATE)
HAVING COUNT(*) > 0
ORDER BY MONTH ASC, CAR_ID DESC
