-- FISH_INFO, FISH_NAME_INFO
-- 잡은 물고기의 길이가 10cm 이하일 경우에는 LENGTH 가 NULL
-- 잡은 BASS와 SNAPPER의 수
-- 컬럼명은 'FISH_COUNT`
SELECT COUNT(*) AS FISH_COUNT
FROM FISH_INFO NATURAL JOIN FISH_NAME_INFO
WHERE FISH_NAME = 'BASS' OR FISH_NAME = 'SNAPPER'