-- 2022년 1월의 카테고리 별 도서 판매량을 합산하고
-- 카테고리(CATEGORY), 총 판매량(TOTAL_SALES) 리스트를 출력
-- 카테고리명을 기준으로 오름차순 정렬

SELECT CATEGORY, SUM(ACC) AS TOTAL_SALES
FROM (SELECT BOOK_ID, SUM(SALES) AS ACC
FROM BOOK_SALES
WHERE YEAR(SALES_DATE) = '2022' AND MONTH(SALES_DATE) = '01'
GROUP BY BOOK_ID) A
NATURAL JOIN BOOK B
GROUP BY CATEGORY
ORDER BY CATEGORY ASC

